apiVersion: machine.sapcloud.io/v1alpha1
kind: MachineClass
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
provider: Alicloud
providerSpec:
  imageID: {{ $machineClass.imageID }}
  instanceType: {{ $machineClass.instanceType }}
  region: {{ $machineClass.region }}
  zoneID: {{ $machineClass.zoneID }}
  securityGroupID: {{ $machineClass.securityGroupID }}
  vSwitchID: {{ $machineClass.vSwitchID }}
  systemDisk:
    category: {{ $machineClass.systemDisk.category }}
    size: {{ $machineClass.systemDisk.size }}
  {{- if $machineClass.dataDisks }}
dataDisks:
  {{ toYaml $machineClass.dataDisks | indent 2 }}
  {{- end }}
instanceChargeType: {{ $machineClass.instanceChargeType }}
internetChargeType: {{ $machineClass.internetChargeType }}
internetMaxBandwidthIn: {{ $machineClass.internetMaxBandwidthIn }}
spotStrategy: {{ $machineClass.spotStrategy }}
keyPairName: {{ $machineClass.keyPairName }}
tags:
  {{ toYaml $machineClass.tags | indent 4 }}
secretRef: # If required
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}