apiVersion: machine.sapcloud.io/v1alpha1
kind: Machine
metadata:
  name: {{ $machine.name }}
  namespace: {{ $.Release.Namespace }}
spec:
  class:
    kind: MachineClass
    name: {{ $machineClass.name }}
    namespace: {{ $.Release.Namespace }}
