apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
  {{- if $machineClass.labels }}
labels:
  {{ toYaml $machineClass.labels | indent 4 }}
  {{- end }}
data:
  userData: {{ $machineClass.secret.userData | b64enc }}
  alicloudAccessKeyID: {{ $machineClass.secret.accessKeyID | b64enc }}
  alicloudAccessKeySecret: {{ $machineClass.secret.accessKeySecret | b64enc }}
### Alternative data keys are:
# accessKeyID: "alicloud-access-key-id" # Alicloud access key ID (base64 encoded)
# accessKeySecret: "alicloud-access-key-secret" # Alicloud secret access key (base64 encoded)
type: Opaque
