apiVersion: v1
kind: Secret
metadata:
  name: {{ $machineClass.name }}
  namespace: {{ $.Release.Namespace }}
  {{- if $machineClass.labels }}
labels:
  {{ toYaml $machineClass.labels | indent 4 }}
  {{- end }}
data:
  userData: {{ $machineClass.secret.userData | b64enc }}
  alicloudAccessKeyID: {{ $machineClass.secret.accessKeyID | b64enc }}
  alicloudAccessKeySecret: {{ $machineClass.secret.accessKeySecret | b64enc }}
type: Opaque